### ISSUE TITLE
Question about SSV2_MC

### ISSUE THREAD

**Issue by Andy1621** [TencentARC/TVTS#1]
Thanks for the great job. One of my questions is how to organize `SSV2_MC`. The code shows that there are `options` and `answer` in the annotations, which are different from the original annotations.

https://github.com/TencentARC/TVTS/blob/290a63efd63f40012e0b6dafd9954dbac40db41d/v2/data_loader/SSV2_mc_dataset.py#L70-L72

Could you please share the annotation files for `SSV2_MC`?

**Comment by stdKonjac** [comment]
Hi Andy, we have provided the annotation files for SSV2_MC in the Google Drive link (meta_data/ssv2/mc/val.jsonl), which can be found in our README.md.
Here's the link: https://drive.google.com/file/d/1EOdB1MmPUHvHDW2le7WbAC1fbDV6LOTM/view?usp=sharing

**Comment by Andy1621** [comment]
Thanks for your fast response!
